# Site settings
title: Canned Emails
description: >
  a minimal site with prewritten emails

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://canned-emails.lightrains.com" # the base hostname & protocol for your site

permalink: /email/:title

author:
  fullname: Nikhil Mohan
  github: niksmac/Canned-Emails.git
  google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown
