# Site settings
title: Canned Emails
description: >
  Canned Emails is a minimal site with prewritten emails, useful for people who prefer easy way of doing things.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://canned-emails.lightrains.com" # the base hostname & protocol for your site

cover: /assets/img/canned-emails.png

permalink: /email/:title

author:
  fullname: Nikhil Mohan
  github: niksmac/Canned-Emails.git
  google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown
